language = "C++"
namespace = "rm_motors_can"
include_guard = "RM_MOTORS_CAN_HPP"

[parse]
# generate bindings for dependencies
parse_deps = true
# but actually only this crate and the one dependency
include = ["rm_motors_can_cpp", "rm_motors_can"]
# and yes, I really do mean this one
extra_bindings = ["rm_motors_can"]
# force cbindgen to expand macros (which generate the wrapper functions) before creating a header file.
# this doesn't work, do manually in build.rs instead
#expand = ["rm_motors_can_cpp"]